version: '3.8'
services:
  api:
    build: .
    container_name: benocode-services
    restart: always
    networks:
    - internal
    - traefik_net
    labels:
    - traefik.enable=true
    - traefik.http.routers.api.rule=Host(`namkhoiapi.nexpo.vn`)
    - traefik.http.routers.api.entrypoints=websecure
    - traefik.http.routers.api.tls.certresolver=myresolver
    - traefik.http.services.api.loadbalancer.server.port=8000
    - traefik.docker.network=app-network
networks:
  internal:
    driver: bridge
  traefik_net:
    external: true
    name: app-network
